apiVersion: v1
kind: Service
metadata:
  name: add-team-member
  namespace: ci
spec:
  type: ClusterIP
  selector:
    app: add-team-member
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
